# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/prefect/Code/C++/Neuro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/prefect/Code/C++/Neuro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prefect/Code/C++/Neuro/CMakeFiles /home/prefect/Code/C++/Neuro//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prefect/Code/C++/Neuro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Neuro

# Build rule for target.
Neuro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Neuro
.PHONY : Neuro

# fast build rule for target.
Neuro/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/build
.PHONY : Neuro/fast

src/Algorithm.o: src/Algorithm.cpp.o
.PHONY : src/Algorithm.o

# target to build an object file
src/Algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Algorithm.cpp.o
.PHONY : src/Algorithm.cpp.o

src/Algorithm.i: src/Algorithm.cpp.i
.PHONY : src/Algorithm.i

# target to preprocess a source file
src/Algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Algorithm.cpp.i
.PHONY : src/Algorithm.cpp.i

src/Algorithm.s: src/Algorithm.cpp.s
.PHONY : src/Algorithm.s

# target to generate assembly for a file
src/Algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Algorithm.cpp.s
.PHONY : src/Algorithm.cpp.s

src/BasicOperations.o: src/BasicOperations.cpp.o
.PHONY : src/BasicOperations.o

# target to build an object file
src/BasicOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/BasicOperations.cpp.o
.PHONY : src/BasicOperations.cpp.o

src/BasicOperations.i: src/BasicOperations.cpp.i
.PHONY : src/BasicOperations.i

# target to preprocess a source file
src/BasicOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/BasicOperations.cpp.i
.PHONY : src/BasicOperations.cpp.i

src/BasicOperations.s: src/BasicOperations.cpp.s
.PHONY : src/BasicOperations.s

# target to generate assembly for a file
src/BasicOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/BasicOperations.cpp.s
.PHONY : src/BasicOperations.cpp.s

src/GcdModule.o: src/GcdModule.cpp.o
.PHONY : src/GcdModule.o

# target to build an object file
src/GcdModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/GcdModule.cpp.o
.PHONY : src/GcdModule.cpp.o

src/GcdModule.i: src/GcdModule.cpp.i
.PHONY : src/GcdModule.i

# target to preprocess a source file
src/GcdModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/GcdModule.cpp.i
.PHONY : src/GcdModule.cpp.i

src/GcdModule.s: src/GcdModule.cpp.s
.PHONY : src/GcdModule.s

# target to generate assembly for a file
src/GcdModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/GcdModule.cpp.s
.PHONY : src/GcdModule.cpp.s

src/Matrix.o: src/Matrix.cpp.o
.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i
.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s
.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/Network.o: src/Network.cpp.o
.PHONY : src/Network.o

# target to build an object file
src/Network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Network.cpp.o
.PHONY : src/Network.cpp.o

src/Network.i: src/Network.cpp.i
.PHONY : src/Network.i

# target to preprocess a source file
src/Network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Network.cpp.i
.PHONY : src/Network.cpp.i

src/Network.s: src/Network.cpp.s
.PHONY : src/Network.s

# target to generate assembly for a file
src/Network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Network.cpp.s
.PHONY : src/Network.cpp.s

src/NetworkManager.o: src/NetworkManager.cpp.o
.PHONY : src/NetworkManager.o

# target to build an object file
src/NetworkManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/NetworkManager.cpp.o
.PHONY : src/NetworkManager.cpp.o

src/NetworkManager.i: src/NetworkManager.cpp.i
.PHONY : src/NetworkManager.i

# target to preprocess a source file
src/NetworkManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/NetworkManager.cpp.i
.PHONY : src/NetworkManager.cpp.i

src/NetworkManager.s: src/NetworkManager.cpp.s
.PHONY : src/NetworkManager.s

# target to generate assembly for a file
src/NetworkManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/NetworkManager.cpp.s
.PHONY : src/NetworkManager.cpp.s

src/ParsingModule.o: src/ParsingModule.cpp.o
.PHONY : src/ParsingModule.o

# target to build an object file
src/ParsingModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/ParsingModule.cpp.o
.PHONY : src/ParsingModule.cpp.o

src/ParsingModule.i: src/ParsingModule.cpp.i
.PHONY : src/ParsingModule.i

# target to preprocess a source file
src/ParsingModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/ParsingModule.cpp.i
.PHONY : src/ParsingModule.cpp.i

src/ParsingModule.s: src/ParsingModule.cpp.s
.PHONY : src/ParsingModule.s

# target to generate assembly for a file
src/ParsingModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/ParsingModule.cpp.s
.PHONY : src/ParsingModule.cpp.s

src/Vector.o: src/Vector.cpp.o
.PHONY : src/Vector.o

# target to build an object file
src/Vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Vector.cpp.o
.PHONY : src/Vector.cpp.o

src/Vector.i: src/Vector.cpp.i
.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Vector.cpp.i
.PHONY : src/Vector.cpp.i

src/Vector.s: src/Vector.cpp.s
.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/Vector.cpp.s
.PHONY : src/Vector.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Neuro.dir/build.make CMakeFiles/Neuro.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Neuro"
	@echo "... src/Algorithm.o"
	@echo "... src/Algorithm.i"
	@echo "... src/Algorithm.s"
	@echo "... src/BasicOperations.o"
	@echo "... src/BasicOperations.i"
	@echo "... src/BasicOperations.s"
	@echo "... src/GcdModule.o"
	@echo "... src/GcdModule.i"
	@echo "... src/GcdModule.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Network.o"
	@echo "... src/Network.i"
	@echo "... src/Network.s"
	@echo "... src/NetworkManager.o"
	@echo "... src/NetworkManager.i"
	@echo "... src/NetworkManager.s"
	@echo "... src/ParsingModule.o"
	@echo "... src/ParsingModule.i"
	@echo "... src/ParsingModule.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

